name: dotnet-demo
services:
- name: backend
  project: src/Backend/Backend.csproj
  env:
  - name: MIGRATE
    value: y
- name: frontend
  project: src/Frontend/Frontend.csproj
  replicas: 2
- name: contactdb
  image: docker.io/library/postgres:13
  env:
  - name: POSTGRES_PASSWORD
    value: "pass@word1"
  - name: POSTGRES_USER
    value: postgres
  - name: POSTGRES_DB
    value: contacts
  volumes:
   - source: tye/contactdb
     target: /var/lib/pgsql/data
  bindings:
  - containerPort: 5432
    connectionString: Host=${host};Port=${port};Database=${env:POSTGRES_DB};Username=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};